### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by fantasticit** [fantasticit/wipi#75]
```shell
FROM node:14

RUN apt-get update \
  && apt-get install -y wget gnupg \
  && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
    --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY / /
RUN chmod +x /start.sh


ENV PUPPETEER_SKIP_DOWNLOAD=true

# install global packages
RUN npm install -g yarn pm2 --registry=https://registry.npm.taobao.org --force
RUN npm config set registry https://registry.npm.taobao.org

RUN yarn --unsafe-perm
RUN yarn run build
RUN npm cache clean

EXPOSE 3000
EXPOSE 3001
EXPOSE 4000

CMD ["/start.sh"]
```

```
**/node_modules
node_modules
```

```
#!/bin/bash

google-chrome-stable
yarn run pm2

```

```
version: '3'
services:
  mysql:
    container_name: mysql
    image: 'mysql:5.7'
    restart: always
    privileged: true
    ports:
      - '3306:3306'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'

  app:
    container_name: app
    build: .
    ports:
      - '3000:3000'
      - '3001:3001'
      - '4000:4000'
```
